### PR TITLE
fix(download): Downloading single config Apis now report encountered errors

### LINKED ISSUE #704: Single Configuration Downloads do not report (authentication) Errors to the User
**Describe the bug**
When downloading a single configuration API fails with an HTTP error (tested with authorization error), there is no indication of the error to the user. 

**How to reproduce**
- download a single configuration API like anomaly-detection-service
-  env NEW_CLI=1 ENV_TOKEN=NOT_A_TOKEN_AT_ALL monaco download -v -a anomaly-detection-services -e environment.yaml

**Expected behavior**
Monaco prints an error about the failed HTTP call.

**Log output**

Single Config API with no error log: 
```
> env NEW_CLI=1 ENV_TOKEN=NOT_A_TOKEN_AT_ALL monaco download -v -a anomaly-detection-services -e environment.yaml
You are using the new CLI structure which is currently in Beta.

Please provide feedback here:
  https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/issues/45.

We plan to make this CLI GA in version 2.0.0

2022-07-27 15:21:49 DEBUG request log not activated
2022-07-27 15:21:49 DEBUG response log not activated
2022-07-27 15:21:49 INFO  Dynatrace Monitoring as Code v1.8.0
2022-07-27 15:21:49 INFO  Creating base project name ojq
2022-07-27 15:21:49 WARN  You used an old token format. Please consider switching to the new 1.205+ token format.
2022-07-27 15:21:49 WARN  More information: https://www.dynatrace.com/support/help/dynatrace-api/basics/dynatrace-api-authentication/#-dynatrace-version-1205--token-format
2022-07-27 15:21:49 INFO   --- GETTING CONFIGS for anomaly-detection-services
2022-07-27 15:21:49 INFO  END downloading info ojq
```

API error (caught earlier in the code) for a regular API: 
```
env NEW_CLI=1 OJQ_TOKEN=NOT_A_TOKEN_AT_ALL monaco download -v -a custom-service-java -e ojq.yaml
You are using the new CLI structure which is currently in Beta.

Please provide feedback here:
  https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/issues/45.

We plan to make this CLI GA in version 2.0.0

2022-07-27 15:22:06 DEBUG request log not activated
2022-07-27 15:22:06 DEBUG response log not activated
2022-07-27 15:22:06 INFO  Dynatrace Monitoring as Code v1.8.0
2022-07-27 15:22:06 INFO  Creating base project name ojq
2022-07-27 15:22:06 WARN  You used an old token format. Please consider switching to the new 1.205+ token format.
2022-07-27 15:22:06 WARN  More information: https://www.dynatrace.com/support/help/dynatrace-api/basics/dynatrace-api-authentication/#-dynatrace-version-1205--token-format
2022-07-27 15:22:06 INFO   --- GETTING CONFIGS for custom-service-java
2022-07-27 15:22:07 ERROR error getting client list from api custom-service-java Failed to get existing configs for api custom-service-java (HTTP 401)!
    Response was: {"error":{"code":401,"message":"Token Authentication failed"}}
2022-07-27 15:22:07 ERROR error getting configs from API custom-service-java %!v(MISSING)
2022-07-27 15:22:07 INFO  END downloading info ojq
```

**Additional context**
Single Configuration API downloads hit a different codepath than regular downloads.
https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/414cc2ded8682651356b26bff4c3be36fa354417/pkg/download/download.go#L166

### PR DESCRIPTION
**Pull request by Laubi**
Fixes #704 

Output w/ -v
```2022-07-28 12:09:57 DEBUG request log not activated
2022-07-28 12:09:57 DEBUG response log not activated
2022-07-28 12:09:57 INFO  Dynatrace Monitoring as Code v1.8.1
2022-07-28 12:09:57 INFO  Creating base project name foo
2022-07-28 12:09:57 WARN  You used an old token format. Please consider switching to the new 1.205+ token format.
2022-07-28 12:09:57 WARN  More information: https://www.dynatrace.com/support/help/dynatrace-api/basics/dynatrace-api-authentication/#-dynatrace-version-1205--token-format
2022-07-28 12:09:57 INFO   --- GETTING CONFIGS for anomaly-detection-services
2022-07-28 12:09:57 DEBUG No previously downloaded configs found.
2022-07-28 12:09:57 ERROR error getting detail for API anomaly-detection-services for entity anomaly-detection-services
2022-07-28 12:09:57 ERROR error getting detail anomaly-detection-services from API
2022-07-28 12:09:57 ERROR error creating config api json file: Failed to get existing configs for api anomaly-detection-services (HTTP 401)!
    Response was: {"error":{"code":401,"message":"Token Authentication failed"}}
2022-07-28 12:09:57 ERROR error getting configs from API anomaly-detection-services
2022-07-28 12:09:57 ERROR error while downloading configs for environment foo
2022-07-28 12:09:57 ERROR There were some errors while downloading the environment configs, please check the logs
```

### CODE REVIEW

File: pkg/rest/client.go [hunk 1]
```diff
@@ -102,7 +107,7 @@ func NewDynatraceClient(environmentUrl, token string) (DynatraceClient, error) {
 		return nil, errors.New("environment url " + environmentUrl + " was not valid")
 	}
 
-	if parsedUrl.Scheme != "https" {
+	if parsedUrl.Scheme != "https" && !skipHttpsCheck {
```
Comment (Laubi) [inline pkg/rest/client.go:110]: Tbh not a fan of this, but testing with a TLS server is not easily possible. https://stackoverflow.com/a/54955508

File: pkg/download/download_test.go [hunk 2]
```diff
@@ -39,7 +39,7 @@ func TestGetConfigs(t *testing.T) {
 	fileManager := util.CreateTestFileSystem()
 	envs["e1"] = env
 	err := getConfigs(fileManager, "", envs, "")
-	assert.NilError(t, err)
+	assert.ErrorContains(t, err, "There were some errors")
```
Comment (UnseenWizzard) [inline pkg/download/download_test.go:42]: Why is test changed to assume an error? This looks like a basic sunny case :/

File: pkg/rest/client.go [hunk 3]
```diff
@@ -155,6 +160,10 @@ func (d *dynatraceClientImpl) ReadById(api Api, id string) (json []byte, err err
 
 	response, err := get(d.client, url, d.token)
 
+	if !success(response) {
+		return nil, fmt.Errorf("Failed to get existing configs for api %v (HTTP %v)!\n    Response was: %v", api.GetId(), response.StatusCode, string(response.Body))
```
Comment (UnseenWizzard) [inline pkg/rest/client.go:164]:
```suggestion
		return nil, fmt.Errorf("Failed to get existing config for api %v (HTTP %v)!\n    Response was: %v", api.GetId(), response.StatusCode, string(response.Body))
```

I'd assume `ReadById` gets a single object and this line is copy paste from somewhere else that read several

File: pkg/rest/client.go (hunk 1 above)
Comment (UnseenWizzard) [reply pkg/rest/client.go:110]: Hm... the way I understand the base question (https://stackoverflow.com/q/54899550) this would work for the client produced by the httptest tls server. 

So maybe rather than just added the skip option change newDynatraceClient to take the client as input?
It otherwise just creates a base client on line 122, you can pass that in from the public one, and plug in the correct test client for testing

File: pkg/download/download_test.go (hunk 2 above)
Comment (Laubi) [reply pkg/download/download_test.go:42]: I thought the same! Before, the errors were simply not returned. 

The error that occurs is also a funny one IMO. Because Monaco actually tries to query the configs from `https://test.live.dynatrace.com`, fails because it is an unknown tenant, and now also returns the error. 
I think we have to re-engineer quite some parts in Monaco to make it properly testable with mock HTTP clients.

Comment (UnseenWizzard) [reply pkg/download/download_test.go:42]: Okay, I guess it would make sense to start on that with download in v2.

The dep inversion/injection pattern you've already started with setup in a public method and injection into the private one seems to work quite nicely and is a non-invasive change - you can refactor method per method keeping the public interface unchanged while enabling testing :)

**Review by UnseenWizzard — APPROVED** [review]
