### PR TITLE
fix: References on pre-existing SLOs do not work

### LINKED ISSUE #288: References on pre-existing SLOs do not work
**Describe the bug**
When referencing SLOs in other configs, `monaco` fails to resolve the dependency when the given SLO config is already present in the environment.

**How to reproduce**
* Create an SLO
* Reference an SLO in another config (e.g. a dashboard)
* Run `monaco` twice

**Additional context**
The problem is that we assume that the SLO API returns the `id` of the updated SLO (after doing a `PUT`) within the `Location` response header. However, this only happens in `POST`. For a `PUT`, we need to use the `id` we get from the `GET (all)` request.

### PR DESCRIPTION
**Pull request by didiladi**
The SLO API returns http status code `200` or `201` when updating an
existing config. Previously, `monaco` just listened for the `204` status
code on update. This commit changes the behavior and makes the response
checking more explicit.

fixes #288

### CODE REVIEW

File: pkg/rest/config_upload.go [hunk 1]
```diff
@@ -57,6 +59,18 @@ func upsertDynatraceObject(client *http.Client, fullUrl string, objectName strin
...
+
+		if success(resp) {
+			util.Log.Debug("\t\t\tUpdated existing object for %s (%s)", objectName, existingObjectId)
+			return api.DynatraceEntity{
+				Id:          existingObjectId,
+				Name:        objectName,
+				Description: "Updated existing object",
+			}, nil
+		} else {
+			return dtEntity, fmt.Errorf("Failed to update DT object %s (HTTP %d)!\n    Response was: %s", objectName, resp.StatusCode, string(resp.Body))
```
Comment (patrickpichler) [inline pkg/rest/config_upload.go:71]: Just to be consistent, could you please return `api.DynatraceEntity{}` here? 
(Also to make it more explicit)

File: pkg/rest/config_upload.go [hunk 2]
```diff
@@ -90,17 +104,9 @@ func upsertDynatraceObject(client *http.Client, fullUrl string, objectName strin
...
-	}
-	if updateSuccess(resp) {
-		util.Log.Debug("\t\t\tUpdated existing object for %s (%s)", objectName, existingObjectId)
-		return api.DynatraceEntity{
-			Id:          existingObjectId,
-			Name:        objectName,
-			Description: "Updated existing object",
-		}, nil
+		if !success(resp) {
+			return dtEntity, fmt.Errorf("Failed to create DT object %s (HTTP %d)!\n    Response was: %s", objectName, resp.StatusCode, string(resp.Body))
```
Comment (patrickpichler) [inline pkg/rest/config_upload.go:108]: The same here

**Review by patrickpichler — DISMISSED** [review]
All in all LGTM 

Just two small nitpicks.

File: pkg/rest/config_upload.go (hunk 1 above)
Comment (UnseenWizzard) [reply pkg/rest/config_upload.go:71]: it will already be that from the var on line 33

But yes, we seem to use that very inconsistently in this method (and we're generally inconsistent e.g. on named return values)

Maybe a codestyle thing we should tackle separate from this?

**Review by UnseenWizzard — APPROVED** [review]

**Comment by UnseenWizzard** [comment]
LGTM as well - I'd suggest we discuss @patrickpichler 's nitpick in general/removed from this bugfix, we're overall inconsistent with that.

File: pkg/rest/config_upload.go (hunk 1 above)
Comment (patrickpichler) [reply pkg/rest/config_upload.go:71]: Yes, but if anybody would set a property on this var, we would return it without noticing ^^

I agree, that it is a code style topic, but to be at least consistent within the method, 
we should return a new empty struct.

Comment (didiladi) [reply pkg/rest/config_upload.go]: done

File: pkg/rest/config_upload.go (hunk 2 above)
Comment (didiladi) [reply pkg/rest/config_upload.go]: done

**Comment by didiladi** [comment]
I had to add another commit (d9e17ef) to this PR, to fix the integration tests which currently keep failing due to #275.

**Review by patrickpichler — APPROVED** [review]
