### PR TITLE
fix: allow deployment of multiple projects and envs at once

### LINKED ISSUE #429: Unable to deploy multiple projects
`deploy -p="general, prod-saas" -e env -c manifest.yaml`
 ends up in an error, only one project considered

### PR DESCRIPTION
**Pull request by tatomir146**
closes #429

### CODE REVIEW

File: cmd/monaco/v2/deploy/deploy.go [hunk 1]
```diff
@@ -87,7 +87,11 @@ func Deploy(fs afero.Fs, deploymentManifestPath string, specificEnvironment stri
 	}
 
 	if specificProject != "" {
-		filtered, err := filterProjectIdsByName(projects, []string{specificProject})
+		projectsMap := strings.Split(specificProject, ",")
```
Comment (patrickpichler) [inline cmd/monaco/v2/deploy/deploy.go:90]: This is actually a slice and not a map. I would rather call this var `projectsToDeploy` or 
something like this.

File: cmd/monaco/v2/deploy/deploy.go [hunk 2]
```diff
@@ -175,13 +179,13 @@ func printErrorReport(deploymentErrors []error) {
 	groupedConfigErrors := groupConfigErrors(configErrors)
 
 	for project, apiErrors := range groupedConfigErrors {
-		log.Error("==== Project `%s`\n", project)
+		log.Error("==== Project `%s`", project)
```
Comment (patrickpichler) [inline cmd/monaco/v2/deploy/deploy.go:182]: Please undo those changes, as they are completely unrelated to the original bug.

**Review by patrickpichler — COMMENTED** [review]
Overall I would use the string slice parameter type offered by cli instead of
doing the parsing ourselves. The syntax would change a bit though. Instead
of passing in a string separated by `,` you would then need to pass in multiple
`-p` flag values (which I personally would prefer).

File: cmd/monaco/v2/deploy/deploy.go [hunk 3]
```diff
@@ -399,18 +418,21 @@ func getApiNames(apis map[string]api.Api) []string {
...
+	for _, name := range names {
+		found := false
+		for _, env := range environments {
+			if env.Name == name {
+				result = append(result, env)
+				found = true
+			}
+		}
+		if !found {
+			return nil, fmt.Errorf("no environment found `%s`", name)
```
Comment (patrickpichler) [inline cmd/monaco/v2/deploy/deploy.go:433]: Could we maybe collect all potential errors here?
I guess it is better for the end user if they see in one
go, what envs do not exist.

Comment (patrickpichler) [reply cmd/monaco/v2/deploy/deploy.go:433]: We might want to do the same for projects

File: cmd/monaco/v2/deploy/deploy.go [hunk 4]
```diff
@@ -86,30 +86,49 @@ func Deploy(fs afero.Fs, deploymentManifestPath string, specificEnvironment stri
 		return errors.New("error while loading projects")
 	}
 
-	if specificProject != "" {
-		filtered, err := filterProjectIdsByName(projects, []string{specificProject})
+	err, projects = checkProjectsToDeploy(specificProject, projects, environmentNames)
```
Comment (patrickpichler) [inline cmd/monaco/v2/deploy/deploy.go:89]: Since the method loads projects and not checks them,
could we rename it to `loadProjectsToDeploy` please?

File: cmd/monaco/v2/deploy/deploy.go (hunk 3 above)
Comment (tatomir146) [reply cmd/monaco/v2/deploy/deploy.go:433]: It's already done for projects 
https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/af39771231aedecad2a4558da557123d95c2d7d4/cmd/monaco/v2/deploy/deploy.go#L323

**Comment by tatomir146** [comment]
I guess this lint error `//TODO` will anyways be fixed by @UnseenWizzard with his PR.

**Review by patrickpichler — APPROVED** [review]
