### PR TITLE
Log a warning if project name clashes with API name (#58)

### LINKED ISSUE #58: Case Sensitive Configuration Type Folders
**Describe the bug**
Configuration type folder names are case sensitive. No configuration will be applied if folders are not lowercase.

But, no error is shown if folders are **not** lowercase.

**How to reproduce**
Create a folder called `auto-tag` with valid config. This will work:

```
monaco.exe --environments=environments.yaml
2020-11-20 08:57:32 INFO  Dynatrace Monitoring as Code v1.0.0
2020-11-20 08:57:32 INFO  Executing projects in this order:
2020-11-20 08:57:32 INFO        1: projects\baseconfig\auto-tag (1 configs)
2020-11-20 08:57:32 INFO  Processing environment my_environment...
2020-11-20 08:57:32 INFO        Processing project projects\baseconfig\auto-tag...
2020-11-20 08:57:32 INFO  Deployment finished without errors
```

Delete the tag rule and rename `auto-tag` to `Auto-Tag`. Re-run `monaco`:
```
monaco.exe --environments=environments.yaml
2020-11-20 08:57:32 INFO  Dynatrace Monitoring as Code v1.0.0
2020-11-20 08:57:32 INFO  Executing projects in this order:
2020-11-20 08:57:32 INFO        1: projects\baseconfig\Auto-Tag (0 configs)
2020-11-20 08:57:32 INFO  Processing environment my_environment...
2020-11-20 08:57:32 INFO        Processing project projects\baseconfig\Auto-Tag...
2020-11-20 08:57:32 INFO  Deployment finished without errors
```

This time, no tag rule is created.

**Expected behavior**
Either accept case insensitive foldernames or print a warning for invalid folder names.

### PR DESCRIPTION
**Pull request by didiladi**
This commit introduces a log message if the project folder name clashes
with an API folder of the same name, but different lowercase/uppercase
spelling. Additionally, the readme was changed, to indicate that API
folders need to be defined case-sensitive.

Example of a log line:
```
2020-11-30 10:43:07 WARN  Project Application in folder \
skip-deployment-project clashes with API name application. \
Consider using a different name for your project.
```

fixes #58

### CODE REVIEW

File: pkg/project/project.go [hunk 1]
```diff
@@ -78,12 +78,23 @@ func NewProject(folder string, apis map[string]api.Api, projectRootFolder string
...
 		configs: builder.configs,
 	}, nil
 }
 
+func warnIfProjectNameClashesWithApiName(projectFolderName string, apis map[string]api.Api, projectRootFolder string) {
+
+	lowerCaseProjectFolderName := strings.ToLower(projectFolderName)
+	_, ok := apis[lowerCaseProjectFolderName]
+	if ok {
+		util.Log.Warn("Project %s in folder %s clashes with API name %s. Consider using a different name for your project.", projectFolderName, projectRootFolder, lowerCaseProjectFolderName)
```
Comment (tatomir146) [inline pkg/project/project.go:94]: Nice!

**Review by tatomir146 — DISMISSED** [review]

**Review by UnseenWizzard — APPROVED** [review]

**Comment by UnseenWizzard** [comment]
Awesome :shipit: (:parrot: !)

**Comment by didiladi** [comment]
Just did a rebase with `main`. In that regard GitHub is quite stupid to require a re-review...

**Review by UnseenWizzard — APPROVED** [review]
